### ISSUE TITLE
Main 

### ISSUE THREAD

**Issue by VB10** [MhYldrm/CryptoQuestor#1]
https://github.com/MhYldrm/CryptoQuestor/blob/145d724b2fc5bf0bb24e0219a0b19f8e0c4910d5/lib/main.dart#L24

- Burada static title vs görüyorum daha yeni başladım bunların constt olması lazım
- Localizaiton değerleri const olmalı başka bir sınıfta
- run ap oncesi olan kodlarını başka bir sınıfta yaparsan daha temiz olur

**Comment by MhYldrm** [comment]
Eksiklikler düzeltildi. Projenin tamamında önerilerinize göre geliştirmeler eklendi. Teşekkürler <3
