### ISSUE TITLE
View 2

### ISSUE THREAD

**Issue by VB10** [MhYldrm/CryptoQuestor#10]
https://github.com/MhYldrm/CryptoQuestor/blob/145d724b2fc5bf0bb24e0219a0b19f8e0c4910d5/lib/view/screens/sign_in_page.dart#L13

- çok içe içe bunlar parçalanmalı
- funciton component widget classlara
- dynamic vs bunlaro olmamlaı
- theme dan okuma yapılmalı en kotu 30 degelreır vs bunlar bır yerde toplanamlı

**Comment by MhYldrm** [comment]
Eksiklikler düzeltildi. Projenin tamamında önerilerinize göre geliştirmeler eklendi. Teşekkürler <3
