### ISSUE TITLE
Sub Widget Parçalama

### ISSUE THREAD

**Issue by VB10** [MhYldrm/CryptoQuestor#2]
https://github.com/MhYldrm/CryptoQuestor/blob/145d724b2fc5bf0bb24e0219a0b19f8e0c4910d5/lib/core/components/button/my_custom_button.dart#L6

- Öncelikle tüm açık propretylereine code comment eklemeyi unutma
- onPRessed olanı voidcallback alias atabilirz
- bir code format eksikliği görüyorum
- padding ve height değerleri const olmalı yada dışarıdan alınnmlaı ve misal mycustom button ise myCustomHeigtButton gibi olmalı
- purple olduğunu koddan değil yine commentlerle vs bakmak lazımdı bunları açıklamak laızm

**Comment by MhYldrm** [comment]
Eksiklikler düzeltildi. Projenin tamamında önerilerinize göre geliştirmeler eklendi. Teşekkürler <3
