### ISSUE TITLE
Empty line ve genel

### ISSUE THREAD

**Issue by VB10** [MhYldrm/CryptoQuestor#3]
https://github.com/MhYldrm/CryptoQuestor/blob/145d724b2fc5bf0bb24e0219a0b19f8e0c4910d5/lib/core/components/styles/custom_colors.dart#L3

- Gördüğüm empty line var kaldıralım
- sınıf komple static ondan private consturtro gerekiyor
- code comment ekleyerek değerleirn karşılıklarnı ekleyleim
-   static  Color coinsCardColor değeri const veya final olmadığı için sııkıntı

**Comment by MhYldrm** [comment]
Eksiklikler düzeltildi. Projenin tamamında önerilerinize göre geliştirmeler eklendi. Teşekkürler <3
