### ISSUE TITLE
Class ismi ve private constr

### ISSUE THREAD

**Issue by VB10** [MhYldrm/CryptoQuestor#4]
https://github.com/MhYldrm/CryptoQuestor/blob/145d724b2fc5bf0bb24e0219a0b19f8e0c4910d5/lib/core/components/styles/custom_texts.dart#L1

- bu tarz yerlede private constructor ihitiyacımız var
- tavisyem sub pathleri sub classlara ayırmak misal AppCosntat.image.user
- List dynamic kullanım olmuş bunu düzeltmek lazım
- class ismi ve dosya isimi uyumlu olmalı

**Comment by MhYldrm** [comment]
Eksiklikler düzeltildi. Projenin tamamında önerilerinize göre geliştirmeler eklendi. Teşekkürler <3
