### ISSUE TITLE
M odel

### ISSUE THREAD

**Issue by VB10** [MhYldrm/CryptoQuestor#5]
https://github.com/MhYldrm/CryptoQuestor/blob/145d724b2fc5bf0bb24e0219a0b19f8e0c4910d5/lib/core/models/chart_model.dart#L1

- şimdi burada muhakkak equtable vs kullanarak bu sınıfın immutable olması sağlanlmaı
- x gibi bir kullanım kesinlikle yok bunu daha type safe hale getirmemiz lazım

**Comment by MhYldrm** [comment]
Eksiklikler düzeltildi. Projenin tamamında önerilerinize göre geliştirmeler eklendi. Teşekkürler <3
