### ISSUE TITLE
model v2

### ISSUE THREAD

**Issue by VB10** [MhYldrm/CryptoQuestor#6]
https://github.com/MhYldrm/CryptoQuestor/blob/145d724b2fc5bf0bb24e0219a0b19f8e0c4910d5/lib/core/models/gecko_models.dart#L9

- model için yazıdklarım hepsi için geçerli
- commentli kod bırakmakya çalış
- şu coinModelFromJson vs bunla rdaima static bir sınfın içinde olmalı
- from json to json elle vermeyelim bunlar için json serizalbe 
-  SparklineIn7D bunun yeir başka sınıf

**Comment by MhYldrm** [comment]
Eksiklikler düzeltildi. Projenin tamamında önerilerinize göre geliştirmeler eklendi. Teşekkürler <3
