### ISSUE TITLE
Network manager

### ISSUE THREAD

**Issue by VB10** [MhYldrm/CryptoQuestor#7]
https://github.com/MhYldrm/CryptoQuestor/blob/145d724b2fc5bf0bb24e0219a0b19f8e0c4910d5/lib/core/network/network_manager.dart#L23

- code format sorunları çok bariz
- status modal immuatalbe olmalı 
- NetworkDio Manger sınıfın içinde olan bazı gereksi nulalblelar var misal _Baseurl nulalble ollamaz vs bunlar için daha iyi şeyle reklemek laızm

**Comment by MhYldrm** [comment]
Eksiklikler düzeltildi. Projenin tamamında önerilerinize göre geliştirmeler eklendi. Teşekkürler <3
