### ISSUE TITLE
service

### ISSUE THREAD

**Issue by VB10** [MhYldrm/CryptoQuestor#8]
https://github.com/MhYldrm/CryptoQuestor/blob/145d724b2fc5bf0bb24e0219a0b19f8e0c4910d5/lib/core/services/coin_services.dart#L35

- firebase işlemlerini ayırmak lazım
- fromsjon to json islemleri alsında compute olmalı

**Comment by MhYldrm** [comment]
Eksiklikler düzeltildi. Projenin tamamında önerilerinize göre geliştirmeler eklendi. Teşekkürler <3
