### ISSUE TITLE
View

### ISSUE THREAD

**Issue by VB10** [MhYldrm/CryptoQuestor#9]
https://github.com/MhYldrm/CryptoQuestor/blob/145d724b2fc5bf0bb24e0219a0b19f8e0c4910d5/lib/view/screens/earn_page.dart

- View katmanlarına mixin ekleyerek widget işlemleri ile busines serivse vs ayırmak laızm
- function compnetler widget component olmalı
- çok iç içe girmiş ifler vs olmalmaı daha primitve olmalı
- set state değil en kötü ValueNotifier kullanılmalı

**Comment by MhYldrm** [comment]
Eksiklikler düzeltildi. Projenin tamamında önerilerinize göre geliştirmeler eklendi. Teşekkürler <3
